#include <tmhc/mathf.h>
#include <include_asm.h>

// INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulVec__FPA3_fP8_fvectorT1);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulVec4x4__FPA3_fP8_fvectorT1);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulTransVecOld__FPA3_fP8_fvectorT1);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulTransVec4x4__FPA3_fP8_fvectorT1);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulTransVecFull4x4__FPA3_fP8_fvectorT1);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulMatrix__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulMatrixTP__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulMatrix3x3__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMulMatrixTP3x3__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfAddMatrix3x3__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfAddMatrixTP3x3__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfSubMatrix3x3__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfSubMatrixTP3x3__FPA3_fN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfScaleMatrix3x3__FPA3_fT0f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfVectorCrossUp__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfVectorCrossRight__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfPlaneTest__FP6_planeP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfNormalizeColumns__FPA3_f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfTransposeMatrix__FPA3_fT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotAxisToMatrix__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotAxisToMatrix__FPA3_fP8_fvectorff);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMatricesToRotAxis__FP8_fvectorPA3_fT1);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMatrixToRotAxis__FP8_fvectorPA3_f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfCopyVectorNotAligned__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfCopyMatrixNotAligned__FPA3_fT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfCopyMatrixNoTrans__FPA3_fT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfUnitMatrix__FPA3_f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotMatrixRPH__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotMatrixPRH__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotMatrixRPHNoTrans__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfHPtoVector__FP8_fvectorff);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfViewScreenMatrix__FPA3_fN20ffffffffffff);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfDumpMatrix__FPA3_f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRPHFromMatrix__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfPRHFromMatrix__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotationFromPointToPoint__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMatrixFromPointToPoint__FPA3_fP8_fvectorT1);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotationFromVector__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfHeadingFromPointToPoint__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfHeadingFromVector__FP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfPitchFromPointToPoint__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfPitchFromVector__FP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfCartesianToSpherical__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfCartesianToSpherical__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfSphericalToCartesian__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfSphericalToCartesian__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMatrixFromNormalAlignedY__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMatrixFromNormalAlignedZ__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfDecomposeVector__FP8_fvectorN30);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfClosestApproach__FR8_fvectorN30);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfClosestApproach__FR8_fvectorN30fRf);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfCatRomInit__FRA3_A3_fR8_fvectorN31);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfCatRom__FR8_fvectorRA3_A3_ff);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfOrthonormalize__FPA3_f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfOrthonormalizeOverTime__FPA3_fPi);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRandfND__Fff);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRandND__Fii);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRandf__Fff);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRand__Fii);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRandVector__FP8_fvectorf);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRandInit__Fii);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotAxisToQuaternion__FP8_fvectorT0f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotAxisToQuaternion__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfAxisAngleToQuaternion__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfRotationArcQuaternion__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfNormalizeQuaternion__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfNormalizeQuaternionFromW__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfConcatQuaternions__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfDeConcatQuaternions__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfQuaternionToUpVector__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfQuaternionToForwardVector__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfQuaternionToMatrix4x4__FPA3_fP8_fvector);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfMatrixToQuaternion__FP8_fvectorPA3_f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfUnitizeQuaternion__FP8_fvectorT0f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfQuaternionMulVec__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfQuaternionMulTransVec__FP8_fvectorN20);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfSlerpQuaternion__FP8_fvectorN20f);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfVectorMinMaxGetMac__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfFormatTime__FiPc);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfFormatTimeMS__FiPc);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfInCone__FP8_fvectorT0);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", mathfIntLog2__FUi);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", func_02288400);
INCLUDE_ASM("asm/nonmatchings/tmhc/mathf", func_02288430);

_fvector mathfMulVec(float a[3], _fvector b, _fvector c)
{
    c.x = b.x * a[0];
    c.y = b.y * a[1];
    c.z = b.z * a[2];
    return c;
}